# Generated by Django 4.1.5 on 2023-01-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.TextField(max_length=50)),
                ('meta_data_type', models.TextField(max_length=20)),
                ('resource_url', models.FilePathField(verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='author_artist',
            name='first_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='libraryobject',
            name='description_text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='libraryobject',
            name='title',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='libraryobject',
            name='topic',
            field=models.TextField(max_length=100),
        ),
        migrations.AddField(
            model_name='libraryobject',
            name='archive_details',
            field=models.ManyToManyField(to='homelibrary.archive_details'),
        ),
    ]
