# Generated by Django 4.1.5 on 2023-01-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelibrary', '0002_archive_details_alter_author_artist_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive_details',
            name='meta_data_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='archive_details',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='libraryobject',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='libraryobject',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
